In [1]:
import pandas as pd

In [2]:
d_df = pd.read_csv("data.csv")
d_df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [3]:
d_df.duplicated().any()

np.True_

In [4]:
d_df = d_df.drop_duplicates()

In [5]:
d_df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [6]:
d_df.info()

<class 'pandas.DataFrame'>
Index: 11199 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11199 non-null  str
 1   Model              11199 non-null  str
 2   Year               11199 non-null  int64
 3   Engine Fuel Type   11196 non-null  str
 4   Engine HP          11130 non-null  float64
 5   Engine Cylinders   11169 non-null  float64
 6   Transmission Type  11199 non-null  str
 7   Driven_Wheels      11199 non-null  str
 8   Number of Doors    11193 non-null  float64
 9   Market Category    7823 non-null   str
 10  Vehicle Size       11199 non-null  str
 11  Vehicle Style      11199 non-null  str
 12  highway MPG        11199 non-null  int64
 13  city mpg           11199 non-null  int64
 14  Popularity         11199 non-null  int64
 15  MSRP               11199 non-null  int64
dtypes: float64(3), int64(5), str(8)
memory usage: 1.5 MB

In [7]:
d_df.dropna(subset="Engine Fuel Type",axis=0,inplace=True)

In [8]:
engine_mean = d_df['Engine HP'].mean()
eng_mode = d_df['Engine Cylinders'].mode()
mark_mode = d_df['Market Category'].mode()

In [9]:
d_df['Engine HP'] = d_df['Engine HP'].fillna(engine_mean)
d_df['Engine Cylinders'] = d_df['Engine Cylinders'].fillna(eng_mode[0])
d_df['Market Category'] = d_df['Market Category'].fillna(mark_mode[0])

In [10]:
d_df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [11]:
d_df.dropna(subset="Number of Doors",axis=0,inplace=True)

In [12]:
d_df.info()

<class 'pandas.DataFrame'>
Index: 11190 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11190 non-null  str
 1   Model              11190 non-null  str
 2   Year               11190 non-null  int64
 3   Engine Fuel Type   11190 non-null  str
 4   Engine HP          11190 non-null  float64
 5   Engine Cylinders   11190 non-null  float64
 6   Transmission Type  11190 non-null  str
 7   Driven_Wheels      11190 non-null  str
 8   Number of Doors    11190 non-null  float64
 9   Market Category    11190 non-null  str
 10  Vehicle Size       11190 non-null  str
 11  Vehicle Style      11190 non-null  str
 12  highway MPG        11190 non-null  int64
 13  city mpg           11190 non-null  int64
 14  Popularity         11190 non-null  int64
 15  MSRP               11190 non-null  int64
dtypes: float64(3), int64(5), str(8)
memory usage: 1.5 MB

In [13]:
d_df.columns = d_df.columns.str.replace(' ', '_')

In [14]:
d_df.columns

Index(['Make', 'Model', 'Year', 'Engine_Fuel_Type', 'Engine_HP',
       'Engine_Cylinders', 'Transmission_Type', 'Driven_Wheels',
       'Number_of_Doors', 'Market_Category', 'Vehicle_Size', 'Vehicle_Style',
       'highway_MPG', 'city_mpg', 'Popularity', 'MSRP'],
      dtype='str')

In [15]:
d_df['Make'].unique()

<StringArray>
[          'BMW',          'Audi',          'FIAT', 'Mercedes-Benz',
      'Chrysler',        'Nissan',         'Volvo',         'Mazda',
    'Mitsubishi',       'Ferrari',    'Alfa Romeo',        'Toyota',
       'McLaren',       'Maybach',       'Pontiac',       'Porsche',
          'Saab',           'GMC',       'Hyundai',      'Plymouth',
         'Honda',    'Oldsmobile',        'Suzuki',          'Ford',
      'Cadillac',           'Kia',       'Bentley',     'Chevrolet',
         'Dodge',   'Lamborghini',       'Lincoln',        'Subaru',
    'Volkswagen',        'Spyker',         'Buick',         'Acura',
   'Rolls-Royce',      'Maserati',         'Lexus',  'Aston Martin',
    'Land Rover',         'Lotus',      'Infiniti',         'Scion',
       'Genesis',        'HUMMER',         'Tesla',       'Bugatti']
Length: 48, dtype: str

In [16]:
def clean_fuel(x):
    x = x.lower()
    if 'premium' in x or 'regular' in x:
        return 'petrol'
    elif 'diesel' in x:
        return 'diesel'
    elif 'electric' in x:
        return 'electric'
    elif 'flex' in x:
        return 'flex_fuel'
    elif 'natural gas' in x:
        return 'natural_gas'
    else:
        return 'other'

d_df['Fuel_Type'] = d_df['Engine_Fuel_Type'].apply(clean_fuel)

In [17]:
d_df.drop('Engine_Fuel_Type', axis=1, inplace=True)

In [18]:
def price_category(x):
    if x < 20000:
        return 'Low'
    elif x < 50000:
        return 'Medium'
    else:
        return 'High'

d_df['price_category'] = d_df['MSRP'].apply(price_category)
d_df.head()

,Make,Model,Year,Engine_HP,Engine_Cylinders,Transmission_Type,Driven_Wheels,Number_of_Doors,Market_Category,Vehicle_Size,Vehicle_Style,highway_MPG,city_mpg,Popularity,MSRP,Fuel_Type,price_category
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135,petrol,Medium
1,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650,petrol,Medium
2,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350,petrol,Medium
3,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450,petrol,Medium
4,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500,petrol,Medium

In [19]:
d_df['Driven_Wheels'].unique()

<StringArray>
['rear wheel drive', 'front wheel drive', 'all wheel drive',
 'four wheel drive']
Length: 4, dtype: str

In [20]:
d_df['Driven_Wheels'] = d_df['Driven_Wheels'].replace({'rear wheel drive' : 'RWD', 'front wheel drive' : 'FWD', 'all wheel drive' :'AWD',
 'four wheel drive':'4WD'})

In [21]:
d_df.head()

,Make,Model,Year,Engine_HP,Engine_Cylinders,Transmission_Type,Driven_Wheels,Number_of_Doors,Market_Category,Vehicle_Size,Vehicle_Style,highway_MPG,city_mpg,Popularity,MSRP,Fuel_Type,price_category
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,RWD,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135,petrol,Medium
1,BMW,1 Series,2011,300.0,6.0,MANUAL,RWD,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650,petrol,Medium
2,BMW,1 Series,2011,300.0,6.0,MANUAL,RWD,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350,petrol,Medium
3,BMW,1 Series,2011,230.0,6.0,MANUAL,RWD,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450,petrol,Medium
4,BMW,1 Series,2011,230.0,6.0,MANUAL,RWD,2.0,Luxury,Compact,Convertible,28,18,3916,34500,petrol,Medium

In [22]:
d_df['Transmission_Type'].unique()

<StringArray>
['MANUAL', 'AUTOMATIC', 'AUTOMATED_MANUAL', 'DIRECT_DRIVE', 'UNKNOWN']
Length: 5, dtype: str

In [23]:
d_df['Transmission_Type'] = d_df['Transmission_Type'].replace({'AUTOMATED_MANUAL':'AUTOMATIC', 'DIRECT_DRIVE':'AUTOMATIC','UNKNOWN':'AUTOMATIC'})

In [24]:
d_df['Market_Category'].unique()

<StringArray>
[                 'Factory Tuner,Luxury,High-Performance',
                                     'Luxury,Performance',
                                'Luxury,High-Performance',
                                                 'Luxury',
                                            'Performance',
                                              'Flex Fuel',
                                  'Flex Fuel,Performance',
                                              'Crossover',
                                              'Hatchback',
                           'Hatchback,Luxury,Performance',
                                       'Hatchback,Luxury',
                         'Luxury,High-Performance,Hybrid',
                                          'Diesel,Luxury',
                                  'Hatchback,Performance',
                    'Hatchback,Factory Tuner,Performance',
                                       'High-Performance',
                         'Factory Tuner,High-Performance',
                                'Exotic,High-Performance',
                  'Exotic,Factory Tuner,High-Performance',
                              'Factory Tuner,Performance',
                                          'Exotic,Luxury',
                         'Exotic,Luxury,High-Performance',
                              'Exotic,Luxury,Performance',
                       'Factory Tuner,Luxury,Performance',
                                       'Flex Fuel,Luxury',
                                       'Crossover,Luxury',
             'Hatchback,Factory Tuner,Luxury,Performance',
                                    'Crossover,Hatchback',
                                                 'Hybrid',
                              'Luxury,Performance,Hybrid',
                    'Crossover,Luxury,Performance,Hybrid',
                           'Crossover,Luxury,Performance',
           'Exotic,Factory Tuner,Luxury,High-Performance',
                      'Flex Fuel,Luxury,High-Performance',
                                    'Crossover,Flex Fuel',
                                                 'Diesel',
                                       'Hatchback,Diesel',
                                'Crossover,Luxury,Diesel',
                      'Crossover,Luxury,High-Performance',
 'Exotic,Flex Fuel,Factory Tuner,Luxury,High-Performance',
               'Exotic,Flex Fuel,Luxury,High-Performance',
                'Exotic,Factory Tuner,Luxury,Performance',
                                       'Hatchback,Hybrid',
                                       'Crossover,Hybrid',
                                'Hatchback,Luxury,Hybrid',
                           'Flex Fuel,Luxury,Performance',
                                  'Crossover,Performance',
                                          'Luxury,Hybrid',
                 'Crossover,Flex Fuel,Luxury,Performance',
                             'Crossover,Flex Fuel,Luxury',
                        'Crossover,Flex Fuel,Performance',
               'Hatchback,Factory Tuner,High-Performance',
                                    'Hatchback,Flex Fuel',
                                   'Factory Tuner,Luxury',
        'Crossover,Factory Tuner,Luxury,High-Performance',
             'Crossover,Factory Tuner,Luxury,Performance',
          'Crossover,Hatchback,Factory Tuner,Performance',
                        'Crossover,Hatchback,Performance',
                                       'Flex Fuel,Hybrid',
                           'Flex Fuel,Performance,Hybrid',
               'Crossover,Exotic,Luxury,High-Performance',
                    'Crossover,Exotic,Luxury,Performance',
                                     'Exotic,Performance',
                  'Exotic,Luxury,High-Performance,Hybrid',
                                'Crossover,Luxury,Hybrid',
        'Flex Fuel,Factory Tuner,Luxury,High-Performance',
                                     'Performance,Hybrid',
                    'Crossover,Factory Tuner,Performance',
                                       'Crossover,Diesel',
                                       'Flex Fuel,Diesel',
                             'Crossover,Hatchback,Luxury']
Length: 71, dtype: str

In [25]:
d_df['Market_Category'] = d_df['Market_Category'].str.split(',').str[-1]

In [26]:
d_df['Vehicle_Style'].unique()

<StringArray>
[              'Coupe',         'Convertible',               'Sedan',
               'Wagon',       '4dr Hatchback',       '2dr Hatchback',
             '4dr SUV',   'Passenger Minivan',       'Cargo Minivan',
     'Crew Cab Pickup',  'Regular Cab Pickup', 'Extended Cab Pickup',
             '2dr SUV',           'Cargo Van',     'Convertible SUV',
       'Passenger Van']
Length: 16, dtype: str

In [27]:
d_df['Vehicle_Style'] = d_df['Vehicle_Style'].replace({'4dr Hatchback' : 'Hatchback',       '2dr Hatchback':'Hatchback',
             '4dr SUV': 'SUV',   'Passenger Minivan' :'Van',       'Cargo Minivan':'Van',
     'Crew Cab Pickup':'Pickup',  'Regular Cab Pickup':'Pickup', 'Extended Cab Pickup':'Pickup',
             '2dr SUV':'SUV',           'Cargo Van':'Van',     'Convertible SUV':'SUV',
       'Passenger Van':'Van'})

In [28]:
d_df = d_df.reset_index(drop=True)

In [29]:
d_df['avg_mpg'] = (d_df['city_mpg'] + d_df['highway_MPG']) / 2

In [30]:
d_df.head(n=15)

,Make,Model,Year,Engine_HP,Engine_Cylinders,Transmission_Type,Driven_Wheels,Number_of_Doors,Market_Category,Vehicle_Size,Vehicle_Style,highway_MPG,city_mpg,Popularity,MSRP,Fuel_Type,price_category,avg_mpg
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,RWD,2.0,High-Performance,Compact,Coupe,26,19,3916,46135,petrol,Medium,22.5
1,BMW,1 Series,2011,300.0,6.0,MANUAL,RWD,2.0,Performance,Compact,Convertible,28,19,3916,40650,petrol,Medium,23.5
2,BMW,1 Series,2011,300.0,6.0,MANUAL,RWD,2.0,High-Performance,Compact,Coupe,28,20,3916,36350,petrol,Medium,24.0
3,BMW,1 Series,2011,230.0,6.0,MANUAL,RWD,2.0,Performance,Compact,Coupe,28,18,3916,29450,petrol,Medium,23.0
4,BMW,1 Series,2011,230.0,6.0,MANUAL,RWD,2.0,Luxury,Compact,Convertible,28,18,3916,34500,petrol,Medium,23.0
5,BMW,1 Series,2012,230.0,6.0,MANUAL,RWD,2.0,Performance,Compact,Coupe,28,18,3916,31200,petrol,Medium,23.0
6,BMW,1 Series,2012,300.0,6.0,MANUAL,RWD,2.0,Performance,Compact,Convertible,26,17,3916,44100,petrol,Medium,21.5
7,BMW,1 Series,2012,300.0,6.0,MANUAL,RWD,2.0,High-Performance,Compact,Coupe,28,20,3916,39300,petrol,Medium,24.0
8,BMW,1 Series,2012,230.0,6.0,MANUAL,RWD,2.0,Luxury,Compact,Convertible,28,18,3916,36900,petrol,Medium,23.0
9,BMW,1 Series,2013,230.0,6.0,MANUAL,RWD,2.0,Luxury,Compact,Convertible,27,18,3916,37200,petrol,Medium,22.5
10,BMW,1 Series,2013,300.0,6.0,MANUAL,RWD,2.0,High-Performance,Compact,Coupe,28,20,3916,39600,petrol,Medium,24.0
11,BMW,1 Series,2013,230.0,6.0,MANUAL,RWD,2.0,Performance,Compact,Coupe,28,19,3916,31500,petrol,Medium,23.5
12,BMW,1 Series,2013,300.0,6.0,MANUAL,RWD,2.0,Performance,Compact,Convertible,28,19,3916,44400,petrol,Medium,23.5
13,BMW,1 Series,2013,230.0,6.0,MANUAL,RWD,2.0,Luxury,Compact,Convertible,28,19,3916,37200,petrol,Medium,23.5
14,BMW,1 Series,2013,320.0,6.0,MANUAL,RWD,2.0,High-Performance,Compact,Convertible,25,18,3916,48250,petrol,Medium,21.5

In [31]:
d_df.to_csv('cleaned_data/data.csv', index=False)